<html>

<head>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type">
    <link rel="stylesheet" type="text/css" href="/lessons/styles.css">
</head>

<body class="c12 doc-content">
    <h1 class="c15 c11">Gestionarea erorilor Ã®n metodele asincrone.</h1>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">Gestionarea erorilor &icirc;n metodele asincrone care utilizeaz&#259; cuvintele
            cheie async &#537;i await are propriile particularit&#259;&#539;i.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c5">Pentru gestionarea erorilor, expresia </span><span class="c7">await </span><span
            class="c4">este plasat&#259; &icirc;ntr-un bloc try:</span></p>
    <p class="c1"><span class="c4"></span></p><a id="t.7d0a47ed640b41e670364b183d1758c4d6267263"></a><a id="t.0"></a>
    <table class="c9">
        <tr class="c10">
            <td class="c17" colspan="1" rowspan="1">
                <p class="c14"><span class="c2">try</span><span class="c0"><br>{<br> &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;PrintAsync(</span><span class="c3">&quot;Hello
                        FDC.COM&quot;</span><span class="c0">);<br> &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;PrintAsync(</span><span
                        class="c3">&quot;Hi&quot;</span><span class="c0">);<br>}<br></span><span
                        class="c2">catch</span><span class="c0">&nbsp;(Exception ex)<br>{<br> &nbsp;
                        &nbsp;Console.WriteLine(ex.Message);<br>}<br> <br></span><span class="c2">async</span><span
                        class="c0">&nbsp;Task </span><span class="c18">PrintAsync</span><span class="c0">(</span><span
                        class="c2">string</span><span class="c0">&nbsp;message)<br>{<br> &nbsp; &nbsp;</span><span
                        class="c8">// dac&#259; lungimea &#537;irului este mai mic&#259; de 3 caractere, gener&#259;m o
                        excep&#539;ie</span><span class="c0"><br> &nbsp; &nbsp;</span><span class="c2">if</span><span
                        class="c0">&nbsp;(message.Length &lt; </span><span class="c13">3</span><span class="c0">)<br>
                        &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="c2">throw</span><span
                        class="c0">&nbsp;</span><span class="c2">new</span><span
                        class="c0">&nbsp;ArgumentException(</span><span class="c3">$&quot;Invalid string length:
                        {message.Length}&quot;</span><span class="c0">);<br> &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;Task.Delay(</span><span
                        class="c13">100</span><span class="c0">); &nbsp; &nbsp; </span><span class="c8">// imita&#539;ia
                        unei opera&#539;ii de lung&#259; durat&#259;</span><span class="c0"><br> &nbsp;
                        &nbsp;Console.WriteLine(message);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">&Icirc;n acest caz, metoda asincron&#259; PrintAsync genereaz&#259; excep&#539;ia
            ArgumentException dac&#259; metoda prime&#537;te un &#537;ir cu lungimea mai mic&#259; de 3
            caractere.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c5">Pentru gestionarea excep&#539;iei &icirc;n metoda Main, expresia await este
            plasat&#259; &icirc;ntr-un bloc try. &Icirc;n rezultat, la executarea apelului </span><span
            class="c5 c6">await PrintAsync(&quot;Hi&quot;)</span><span class="c4">, se va genera o excep&#539;ie.
            Totu&#537;i, programul nu se va opri &icirc;n mod avariat, ci va gestiona excep&#539;ia &#537;i va continua
            calculul.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">Afi&#537;area pe consol&#259; a programului:</span></p>
    <p class="c1"><span class="c4"></span></p><a id="t.d302d60073241e75f297924c8521ac9dd02752cf"></a><a id="t.1"></a>
    <table class="c9">
        <tr class="c10">
            <td class="c17" colspan="1" rowspan="1">
                <p class="c14"><span class="c0">Hello FDC.COM<br>Invalid </span><span class="c2">string</span><span
                        class="c0">&nbsp;length: </span><span class="c13">2</span></p>
            </td>
        </tr>
    </table>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">Trebuie avut &icirc;n vedere c&#259; dac&#259; metoda asincron&#259; are tipul void,
            atunci excep&#539;ia nu se transmite &icirc;n afara metodei, prin urmare, nu vom putea gestiona
            excep&#539;ia la apelul metodei:</span></p>
    <p class="c1"><span class="c4"></span></p><a id="t.54c2454daa973f9aeac826620d8a97ccfe9c053d"></a><a id="t.2"></a>
    <table class="c9">
        <tr class="c10">
            <td class="c17" colspan="1" rowspan="1">
                <p class="c14"><span class="c2">try</span><span class="c0"><br>{<br> &nbsp;
                        &nbsp;PrintAsync(</span><span class="c3">&quot;Hello FDC.COM&quot;</span><span class="c0">);<br>
                        &nbsp; &nbsp;PrintAsync(</span><span class="c3">&quot;Hi&quot;</span><span class="c0">); &nbsp;
                        &nbsp; &nbsp; </span><span class="c8">// aici programul va genera o excep&#539;ie &#537;i se va
                        opri avariat</span><span class="c0"><br> &nbsp; &nbsp;</span><span class="c2">await</span><span
                        class="c0">&nbsp;Task.Delay(</span><span class="c13">1000</span><span class="c0">); </span><span
                        class="c8">// a&#537;tept&#259;m finalizarea sarcinilor</span><span
                        class="c0"><br>}<br></span><span class="c2">catch</span><span class="c0">&nbsp;(Exception ex)
                        &nbsp; &nbsp;</span><span class="c8">// excep&#539;ia NU va fi gestionat&#259;</span><span
                        class="c0"><br>{<br> &nbsp; &nbsp;Console.WriteLine(ex.Message);<br>}<br> <br></span><span
                        class="c2">async</span><span class="c0">&nbsp;</span><span class="c2">void</span><span
                        class="c0">&nbsp;</span><span class="c18">PrintAsync</span><span class="c0">(</span><span
                        class="c2">string</span><span class="c0">&nbsp;message)<br>{<br> &nbsp; &nbsp;</span><span
                        class="c8">// dac&#259; lungimea &#537;irului este mai mic&#259; de 3 caractere, gener&#259;m o
                        excep&#539;ie</span><span class="c0"><br> &nbsp; &nbsp;</span><span class="c2">if</span><span
                        class="c0">&nbsp;(message.Length &lt; </span><span class="c13">3</span><span class="c0">)<br>
                        &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="c2">throw</span><span
                        class="c0">&nbsp;</span><span class="c2">new</span><span
                        class="c0">&nbsp;ArgumentException(</span><span class="c3">$&quot;Invalid string length:
                        {message.Length}&quot;</span><span class="c0">);<br> &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;Task.Delay(</span><span
                        class="c13">100</span><span class="c0">); &nbsp; &nbsp; </span><span class="c8">// imita&#539;ia
                        unei opera&#539;ii de lung&#259; durat&#259;</span><span class="c0"><br> &nbsp;
                        &nbsp;Console.WriteLine(message);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">&Icirc;n acest caz, de&#537;i metodele asincrone sunt apelate &icirc;n blocul try,
            excep&#539;ia nu va fi capturat&#259; &#537;i gestionat&#259;. Acesta este unul dintre dezavantajele
            utiliz&#259;rii metodelor asincrone de tip void. Totu&#537;i, &icirc;n acest caz, putem defini gestionarea
            excep&#539;iei &icirc;n &icirc;ns&#259;&#537;i metoda asincron&#259;:</span></p>
    <p class="c1"><span class="c4"></span></p><a id="t.10b1b57a2aa2fd912cbd061b983c3745a7b68b2c"></a><a id="t.3"></a>
    <table class="c9">
        <tr class="c10">
            <td class="c17" colspan="1" rowspan="1">
                <p class="c14"><span class="c0">PrintAsync(</span><span class="c3">&quot;Hello FDC.COM&quot;</span><span
                        class="c0">);<br>PrintAsync(</span><span class="c3">&quot;Hi&quot;</span><span
                        class="c0">);<br></span><span class="c2">await</span><span
                        class="c0">&nbsp;Task.Delay(</span><span class="c13">1000</span><span class="c0">); </span><span
                        class="c8">// a&#537;tept&#259;m finalizarea sarcinilor</span><span class="c0"><br>
                        <br></span><span class="c2">async</span><span class="c0">&nbsp;</span><span
                        class="c2">void</span><span class="c0">&nbsp;</span><span class="c18">PrintAsync</span><span
                        class="c0">(</span><span class="c2">string</span><span class="c0">&nbsp;message)<br>{<br> &nbsp;
                        &nbsp;</span><span class="c2">try</span><span class="c0"><br> &nbsp; &nbsp;{<br> &nbsp; &nbsp;
                        &nbsp; &nbsp;</span><span class="c8">// dac&#259; lungimea &#537;irului este mai mic&#259; de 3
                        caractere, gener&#259;m o excep&#539;ie</span><span class="c0"><br> &nbsp; &nbsp; &nbsp;
                        &nbsp;</span><span class="c2">if</span><span class="c0">&nbsp;(message.Length &lt; </span><span
                        class="c13">3</span><span class="c0">)<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span
                        class="c2">throw</span><span class="c0">&nbsp;</span><span class="c2">new</span><span
                        class="c0">&nbsp;ArgumentException(</span><span class="c3">$&quot;Invalid string length:
                        {message.Length}&quot;</span><span class="c0">);<br> &nbsp; &nbsp; &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;Task.Delay(</span><span
                        class="c13">100</span><span class="c0">); &nbsp; &nbsp; </span><span class="c8">// imita&#539;ia
                        unei opera&#539;ii de lung&#259; durat&#259;</span><span class="c0"><br> &nbsp; &nbsp; &nbsp;
                        &nbsp;Console.WriteLine(message);<br> &nbsp; &nbsp;}<br> &nbsp; &nbsp;</span><span
                        class="c2">catch</span><span class="c0">&nbsp;(Exception ex)<br> &nbsp; &nbsp;{<br> &nbsp;
                        &nbsp; &nbsp; &nbsp;Console.WriteLine(ex.Message);<br> &nbsp; &nbsp;}<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c16">Investigarea excep&#539;iei.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c5">&Icirc;n caz de eroare, obiectul Task, care reprezint&#259; sarcina asincron&#259;
            &icirc;n care a ap&#259;rut eroarea, are proprietatea </span><span class="c7">IsFaulted </span><span
            class="c4">cu valoarea true. &Icirc;n plus, proprietatea Exception a obiectului Task con&#539;ine toate
            informa&#539;iile despre eroare. S&#259; inspect&#259;m aceast&#259; proprietate:</span></p>
    <p class="c1"><span class="c4"></span></p><a id="t.5b553e21e63c4cda6c28cc76ae71b447105268e1"></a><a id="t.4"></a>
    <table class="c9">
        <tr class="c10">
            <td class="c17" colspan="1" rowspan="1">
                <p class="c14"><span class="c2">var</span><span class="c0">&nbsp;task = PrintAsync(</span><span
                        class="c3">&quot;Hi&quot;</span><span class="c0">);<br></span><span class="c2">try</span><span
                        class="c0"><br>{<br> &nbsp; &nbsp;</span><span class="c2">await</span><span
                        class="c0">&nbsp;task;<br>}<br></span><span class="c2">catch</span><span class="c0"><br>{<br>
                        &nbsp; &nbsp;Console.WriteLine(task.Exception?.InnerException?.Message); </span><span
                        class="c8">// Invalid string length: 2</span><span class="c0"><br> &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c3">$&quot;IsFaulted:
                        {task.IsFaulted}&quot;</span><span class="c0">); &nbsp;</span><span class="c8">// IsFaulted:
                        True</span><span class="c0"><br> &nbsp; &nbsp;Console.WriteLine(</span><span
                        class="c3">$&quot;Status: {task.Status}&quot;</span><span class="c0">); &nbsp; &nbsp; &nbsp;
                        &nbsp;</span><span class="c8">// Status: Faulted</span><span class="c0"><br>}<br>
                        <br></span><span class="c2">async</span><span class="c0">&nbsp;Task </span><span
                        class="c18">PrintAsync</span><span class="c0">(</span><span class="c2">string</span><span
                        class="c0">&nbsp;message)<br>{<br> &nbsp; &nbsp;</span><span class="c8">// dac&#259; lungimea
                        &#537;irului este mai mic&#259; de 3 caractere, gener&#259;m o excep&#539;ie</span><span
                        class="c0"><br> &nbsp; &nbsp;</span><span class="c2">if</span><span
                        class="c0">&nbsp;(message.Length &lt; </span><span class="c13">3</span><span class="c0">)<br>
                        &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="c2">throw</span><span
                        class="c0">&nbsp;</span><span class="c2">new</span><span
                        class="c0">&nbsp;ArgumentException(</span><span class="c3">$&quot;Invalid string length:
                        {message.Length}&quot;</span><span class="c0">);<br> &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;Task.Delay(</span><span
                        class="c13">1000</span><span class="c0">); &nbsp; &nbsp; </span><span class="c8">//
                        imita&#539;ia unei opera&#539;ii de lung&#259; durat&#259;</span><span class="c0"><br> &nbsp;
                        &nbsp;Console.WriteLine(message);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">&#536;i dac&#259; transmitem &icirc;n metod&#259; un &#537;ir cu lungimea mai
            mic&#259; de 3 caractere, task.IsFaulted va fi true.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c16">Gestionarea mai multor excep&#539;ii. WhenAll.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c5">Dac&#259; a&#537;tept&#259;m finalizarea mai multor sarcini simultan, de exemplu, cu
            ajutorul </span><span class="c5 c6">Task.WhenAll</span><span class="c5">, putem ob&#539;ine mai multe
            excep&#539;ii &icirc;n acela&#537;i timp pentru fiecare sarcin&#259; executat&#259;. &Icirc;n acest caz,
            putem ob&#539;ine toate excep&#539;iile din proprietatea </span><span
            class="c5 c6">Exception.InnerExceptions</span><span class="c4">:</span></p>
    <p class="c1"><span class="c4"></span></p><a id="t.9c92d4106b63bae53ad473512e7e9c10a4a7022d"></a><a id="t.5"></a>
    <table class="c9">
        <tr class="c10">
            <td class="c17" colspan="1" rowspan="1">
                <p class="c14"><span class="c8">// definim &#537;i lans&#259;m sarcinile</span><span
                        class="c0"><br></span><span class="c2">var</span><span class="c0">&nbsp;task1 =
                        PrintAsync(</span><span class="c3">&quot;H&quot;</span><span class="c0">);<br></span><span
                        class="c2">var</span><span class="c0">&nbsp;task2 = PrintAsync(</span><span
                        class="c3">&quot;Hi&quot;</span><span class="c0">);<br></span><span class="c2">var</span><span
                        class="c0">&nbsp;allTasks = Task.WhenAll(task1, task2);<br></span><span
                        class="c2">try</span><span class="c0"><br>{<br> &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;allTasks;<br>}<br></span><span
                        class="c2">catch</span><span class="c0">&nbsp;(Exception ex)<br>{<br> &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c3">$&quot;Exception: {ex.Message}&quot;</span><span
                        class="c0">);<br> &nbsp; &nbsp;Console.WriteLine(</span><span class="c3">$&quot;IsFaulted:
                        {allTasks.IsFaulted}&quot;</span><span class="c0">);<br> &nbsp; &nbsp;</span><span
                        class="c2">if</span><span class="c0">(allTasks.Exception </span><span class="c2">is</span><span
                        class="c0">&nbsp;not </span><span class="c2">null</span><span class="c0">)<br> &nbsp;
                        &nbsp;{<br> &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="c2">foreach</span><span
                        class="c0">&nbsp;(</span><span class="c2">var</span><span class="c0">&nbsp;exception
                    </span><span class="c2">in</span><span class="c0">&nbsp;allTasks.Exception.InnerExceptions)<br>
                        &nbsp; &nbsp; &nbsp; &nbsp;{<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c3">$&quot;InnerException:
                        {exception.Message}&quot;</span><span class="c0">);<br> &nbsp; &nbsp; &nbsp; &nbsp;}<br> &nbsp;
                        &nbsp;}<br>}<br> <br></span><span class="c2">async</span><span class="c0">&nbsp;Task
                    </span><span class="c18">PrintAsync</span><span class="c0">(</span><span
                        class="c2">string</span><span class="c0">&nbsp;message)<br>{<br> &nbsp; &nbsp;</span><span
                        class="c8">// dac&#259; lungimea &#537;irului este mai mic&#259; de 3 caractere, gener&#259;m o
                        excep&#539;ie</span><span class="c0"><br> &nbsp; &nbsp;</span><span class="c2">if</span><span
                        class="c0">&nbsp;(message.Length &lt; </span><span class="c13">3</span><span class="c0">)<br>
                        &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="c2">throw</span><span
                        class="c0">&nbsp;</span><span class="c2">new</span><span
                        class="c0">&nbsp;ArgumentException(</span><span class="c3">$&quot;Invalid string:
                        {message}&quot;</span><span class="c0">);<br> &nbsp; &nbsp;</span><span
                        class="c2">await</span><span class="c0">&nbsp;Task.Delay(</span><span
                        class="c13">1000</span><span class="c0">); &nbsp; &nbsp; </span><span class="c8">//
                        imita&#539;ia unei opera&#539;ii de lung&#259; durat&#259;</span><span class="c0"><br> &nbsp;
                        &nbsp;Console.WriteLine(message);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">Aici, &icirc;n dou&#259; apeluri ale metodei PrintAsync sunt transmise valori
            evident incorecte. Astfel, la ambele apeluri se va genera o eroare.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c5">De&#537;i blocul catch, prin variabila </span><span class="c5 c6">Exception
            ex</span><span class="c5">, va primi o singur&#259; excep&#539;ie capturat&#259;, cu ajutorul
            colec&#539;iei</span><span class="c5 c6">&nbsp;Exception.InnerExceptions</span><span class="c4">, vom putea
            ob&#539;ine informa&#539;ii despre toate excep&#539;iile ap&#259;rute.</span></p>
    <p class="c1"><span class="c4"></span></p>
    <p class="c15"><span class="c4">&Icirc;n final, la executarea acestei metode, vom ob&#539;ine urm&#259;toarea
            afi&#537;are pe consol&#259;:</span></p>
    <p class="c1"><span class="c4"></span></p><a id="t.89fff540f23f1be7ec67b8e230c9a7d0d8516d81"></a><a id="t.6"></a>
    <table class="c9">
        <tr class="c10">
            <td class="c17" colspan="1" rowspan="1">
                <p class="c14"><span class="c0">Exception: Invalid </span><span class="c2">string</span><span
                        class="c0">: H<br>IsFaulted: True<br>InnerException: Invalid </span><span
                        class="c2">string</span><span class="c0">: H<br>InnerException: Invalid </span><span
                        class="c2">string</span><span class="c0">: Hi</span></p>
            </td>
        </tr>
    </table>
    <p class="c1"><span class="c4"></span></p>
    <p class="c1"><span class="c4"></span></p>
</body>

</html>