<html>

<head>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type">
    <link rel="stylesheet" type="text/css" href="/lessons/styles.css">
</head>

<body class="c12 doc-content">
    <h1 class="c4 c13">Căutarea blocului catch la tratarea excepțiilor.</h1>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">Dac&#259; codul care declan&#537;eaz&#259; o excep&#539;ie nu este plasat
            &icirc;ntr-un bloc try sau este plasat &icirc;ntr-o construc&#539;ie try..catch care nu con&#539;ine un bloc
            catch corespunz&#259;tor pentru tratarea excep&#539;iei ap&#259;rute, sistemul va c&#259;uta un handler de
            excep&#539;ie corespunz&#259;tor &icirc;n stiva de apeluri.</span></p>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">De exemplu, s&#259; consider&#259;m urm&#259;torul program:</span></p>
    <p class="c0"><span class="c5"></span></p><a id="t.d1217c7fa38d893595b8695867509d6888bd965a"></a><a id="t.0"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c2">try</span><span class="c1"><br>{<br> &nbsp;
                        &nbsp;TestClass.Method1();<br>}<br></span><span class="c2">catch</span><span
                        class="c1">&nbsp;(DivideByZeroException ex)<br>{<br> &nbsp; &nbsp;Console.WriteLine(</span><span
                        class="c8">$&quot;Catch &icirc;n Main : {ex.Message}&quot;</span><span
                        class="c1">);<br>}<br></span><span class="c2">finally</span><span class="c1"><br>{<br> &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally &icirc;n
                        Main&quot;</span><span class="c1">);<br>}<br>Console.WriteLine(</span><span
                        class="c8">&quot;Sf&acirc;r&#537;itul metodei Main&quot;</span><span
                        class="c1">);<br><br></span><span class="c2">class</span><span class="c1">&nbsp;</span><span
                        class="c15">TestClass</span><span class="c1"><br>{<br> &nbsp; &nbsp;</span><span
                        class="c2">public</span><span class="c1">&nbsp;</span><span class="c2">static</span><span
                        class="c1">&nbsp;</span><span class="c2">void</span><span class="c1">&nbsp;</span><span
                        class="c15">Method1</span><span class="c1">()<br> &nbsp; &nbsp;{<br> &nbsp; &nbsp; &nbsp;
                        &nbsp;</span><span class="c2">try</span><span class="c1"><br> &nbsp; &nbsp; &nbsp; &nbsp;{<br>
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Method2();<br> &nbsp; &nbsp; &nbsp; &nbsp;}<br> &nbsp;
                        &nbsp; &nbsp; &nbsp;</span><span class="c2">catch</span><span
                        class="c1">&nbsp;(IndexOutOfRangeException ex)<br> &nbsp; &nbsp; &nbsp; &nbsp;{<br> &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Console.WriteLine(</span><span class="c8">$&quot;Catch
                        &icirc;n Method1 : {ex.Message}&quot;</span><span class="c1">);<br> &nbsp; &nbsp; &nbsp;
                        &nbsp;}<br> &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="c2">finally</span><span
                        class="c1"><br> &nbsp; &nbsp; &nbsp; &nbsp;{<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally &icirc;n
                        Method1&quot;</span><span class="c1">);<br> &nbsp; &nbsp; &nbsp; &nbsp;}<br> &nbsp; &nbsp;
                        &nbsp; &nbsp;Console.WriteLine(</span><span class="c8">&quot;Sf&acirc;r&#537;itul metodei
                        Method1&quot;</span><span class="c1">);<br> &nbsp; &nbsp;}<br> &nbsp; &nbsp;</span><span
                        class="c2">static</span><span class="c1">&nbsp;</span><span class="c2">void</span><span
                        class="c1">&nbsp;</span><span class="c15">Method2</span><span class="c1">()<br> &nbsp;
                        &nbsp;{<br> &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="c2">try</span><span class="c1"><br>
                        &nbsp; &nbsp; &nbsp; &nbsp;{<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span
                        class="c2">int</span><span class="c1">&nbsp;x = </span><span class="c9">8</span><span
                        class="c1">;<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span
                        class="c2">int</span><span class="c1">&nbsp;y = x / </span><span class="c9">0</span><span
                        class="c1">;<br> &nbsp; &nbsp; &nbsp; &nbsp;}<br> &nbsp; &nbsp; &nbsp; &nbsp;</span><span
                        class="c2">finally</span><span class="c1"><br> &nbsp; &nbsp; &nbsp; &nbsp;{<br> &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally &icirc;n
                        Method2&quot;</span><span class="c1">);<br> &nbsp; &nbsp; &nbsp; &nbsp;}<br> &nbsp; &nbsp;
                        &nbsp; &nbsp;Console.WriteLine(</span><span class="c8">&quot;Sf&acirc;r&#537;itul metodei
                        Method2&quot;</span><span class="c1">);<br> &nbsp; &nbsp;}<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">&Icirc;n acest caz, stiva de apeluri arat&#259; astfel: metoda Main apeleaz&#259;
            metoda Method1, care la r&acirc;ndul s&#259;u apeleaz&#259; metoda Method2. &Icirc;n metoda Method2 se
            genereaz&#259; o excep&#539;ie de tip DivideByZeroException. Vizual, stiva de apeluri poate fi
            reprezentat&#259; astfel:</span></p>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span
            style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 182.00px; height: 181.00px;"><img
                alt="" src="images/image1.png"
                style="width: 182.00px; height: 181.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);"
                title=""></span></p>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">Ce se &icirc;nt&acirc;mpl&#259; &icirc;n acest caz c&acirc;nd se genereaz&#259; o
            excep&#539;ie?</span></p>
    <p class="c0"><span class="c5"></span></p>
    <ol class="c11 lst-kix_p8w9sfeeyr2z-0 start" start="1">
        <li class="c4 c7 li-bullet-0"><span class="c5">Metoda Main apeleaz&#259; metoda Method1, iar aceasta
                apeleaz&#259; metoda Method2, unde se genereaz&#259; excep&#539;ia DivideByZeroException.</span></li>
    </ol>
    <p class="c0 c16"><span class="c5"></span></p>
    <ol class="c11 lst-kix_p8w9sfeeyr2z-0" start="2">
        <li class="c4 c7 li-bullet-0"><span class="c5">Sistemul vede c&#259; codul care a generat excep&#539;ia este
                plasat &icirc;ntr-o construc&#539;ie try..catch:</span></li>
    </ol>
    <p class="c0"><span class="c5"></span></p><a id="t.72fd81046e2bae319c9980108a43a4d1b9b8474a"></a><a id="t.1"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c2">try</span><span class="c1"><br>{<br> &nbsp; &nbsp;</span><span
                        class="c2">int</span><span class="c1">&nbsp;x = </span><span class="c9">8</span><span
                        class="c1">;<br> &nbsp; &nbsp;</span><span class="c2">int</span><span class="c1">&nbsp;y = x /
                    </span><span class="c9">0</span><span class="c1">;<br>}<br></span><span
                        class="c2">finally</span><span class="c1"><br>{<br> &nbsp; &nbsp;Console.WriteLine(</span><span
                        class="c8">&quot;Bloc finally &icirc;n Method2&quot;</span><span class="c1">);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">Sistemul caut&#259; &icirc;n aceast&#259; construc&#539;ie un bloc catch care s&#259;
            trateze excep&#539;ia DivideByZeroException. Cu toate acestea, nu exist&#259; un astfel de bloc
            catch.</span></p>
    <p class="c0"><span class="c5"></span></p>
    <ol class="c11 lst-kix_tzrnyu4np3pg-0 start" start="3">
        <li class="c4 c7 li-bullet-0"><span class="c5">Sistemul coboar&#259; &icirc;n stiva de apeluri &icirc;n metoda
                Method1, care a apelat Method2. Aici, apelul Method2 este plasat &icirc;ntr-o construc&#539;ie
                try..catch:</span></li>
    </ol>
    <p class="c0"><span class="c5"></span></p><a id="t.8ee134c7382b6fcf5aac0558060fc3f61a7bb999"></a><a id="t.2"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c2">try</span><span class="c1"><br>{<br> &nbsp;
                        &nbsp;Method2();<br>}<br></span><span class="c2">catch</span><span
                        class="c1">&nbsp;(IndexOutOfRangeException ex)<br>{<br> &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c8">$&quot;Catch &icirc;n Method1 :
                        {ex.Message}&quot;</span><span class="c1">);<br>}<br></span><span class="c2">finally</span><span
                        class="c1"><br>{<br> &nbsp; &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally
                        &icirc;n Method1&quot;</span><span class="c1">);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">Sistemul caut&#259; &#537;i aici un bloc catch care s&#259; trateze excep&#539;ia
            DivideByZeroException, dar nu g&#259;se&#537;te unul.</span></p>
    <p class="c0"><span class="c5"></span></p>
    <ol class="c11 lst-kix_c93m7or1vr27-0 start" start="4">
        <li class="c4 c7 li-bullet-0"><span class="c5">Sistemul coboar&#259; mai departe &icirc;n stiva de apeluri
                &icirc;n metoda Main, care a apelat Method1. Aici, apelul Method1 este plasat &icirc;ntr-o
                construc&#539;ie try..catch:</span></li>
    </ol>
    <p class="c0"><span class="c5"></span></p><a id="t.f051703af2793763abb6a170588e45558a984dbd"></a><a id="t.3"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c2">try</span><span class="c1"><br>{<br> &nbsp;
                        &nbsp;TestClass.Method1();<br>}<br></span><span class="c2">catch</span><span
                        class="c1">&nbsp;(DivideByZeroException ex)<br>{<br> &nbsp; &nbsp;Console.WriteLine(</span><span
                        class="c8">$&quot;Catch &icirc;n Main : {ex.Message}&quot;</span><span
                        class="c1">);<br>}<br></span><span class="c2">finally</span><span class="c1"><br>{<br> &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally &icirc;n
                        Main&quot;</span><span class="c1">);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">Sistemul g&#259;se&#537;te &icirc;n aceast&#259; construc&#539;ie un bloc catch care
            trateaz&#259; excep&#539;ia DivideByZeroException.</span></p>
    <p class="c0"><span class="c5"></span></p>
    <ol class="c11 lst-kix_e3ecls5rpn29-0 start" start="5">
        <li class="c4 c7 li-bullet-0"><span class="c5">&Icirc;n cele din urm&#259;, sistemul a g&#259;sit blocul catch
                corespunz&#259;tor &icirc;n metoda Main pentru a trata excep&#539;ia ap&#259;rut&#259; &icirc;n metoda
                Method2 - adic&#259; &icirc;n metoda ini&#539;ial&#259; unde a ap&#259;rut excep&#539;ia. Dar acest bloc
                catch NU se execut&#259; imediat. Sistemul urc&#259; &icirc;napoi pe stiva de apeluri &icirc;n
                v&acirc;rful metodei Method2 &#537;i execut&#259; blocul finally:</span></li>
    </ol>
    <p class="c0"><span class="c5"></span></p><a id="t.9f80c1cf2222c39ad3657875d7d6b066f8da478a"></a><a id="t.4"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c2">finally</span><span class="c1"><br>{<br> &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally &icirc;n
                        Method2&quot;</span><span class="c1">);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <ol class="c11 lst-kix_vb0h2v3vhxk1-0 start" start="6">
        <li class="c4 c7 li-bullet-0"><span class="c5">Apoi, sistemul coboar&#259; &icirc;n stiva de apeluri &icirc;n
                metoda Method1 &#537;i execut&#259; blocul finally:</span></li>
    </ol>
    <p class="c0"><span class="c5"></span></p><a id="t.1a53fb21b94eddf964d5207065cd046fbaab8191"></a><a id="t.5"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c2">finally</span><span class="c1"><br>{<br> &nbsp;
                        &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally &icirc;n
                        Method1&quot;</span><span class="c1">);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <ol class="c11 lst-kix_sgg12vgngln8-0 start" start="7">
        <li class="c4 c7 li-bullet-0"><span class="c5">Apoi, sistemul coboar&#259; &icirc;n stiva de apeluri &icirc;n
                metoda Main &#537;i execut&#259; blocul catch g&#259;sit &#537;i blocul finally urm&#259;tor:</span>
        </li>
    </ol>
    <p class="c0"><span class="c5"></span></p>
    <p class="c0"><span class="c5"></span></p><a id="t.96cca998fa956eb485160bc8408b9c8db733dbf4"></a><a id="t.6"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c2">catch</span><span class="c1">&nbsp;(DivideByZeroException ex)<br>{<br>
                        &nbsp; &nbsp;Console.WriteLine(</span><span class="c8">$&quot;Catch &icirc;n Main :
                        {ex.Message}&quot;</span><span class="c1">);<br>}<br></span><span class="c2">finally</span><span
                        class="c1"><br>{<br> &nbsp; &nbsp;Console.WriteLine(</span><span class="c8">&quot;Bloc finally
                        &icirc;n Main&quot;</span><span class="c1">);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <ol class="c11 lst-kix_w4qbs58yheqv-0 start" start="8">
        <li class="c4 c7 li-bullet-0"><span class="c5">Dup&#259; aceasta, se execut&#259; codul care urmeaz&#259;
                construc&#539;iei try..catch &icirc;n metoda Main:</span></li>
    </ol>
    <p class="c0"><span class="c5"></span></p><a id="t.897345b91b6c73e997f7f7aec890a3eeb7e21789"></a><a id="t.7"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c1">Console.WriteLine(</span><span class="c8">&quot;Sf&acirc;r&#537;itul
                        metodei Main&quot;</span><span class="c1">);</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">Este important de men&#539;ionat c&#259; codul care urmeaz&#259; dup&#259;
            construc&#539;ia try..catch &icirc;n metodele Method1 &#537;i Method2 nu se execut&#259;, deoarece
            handler-ul de excep&#539;ii a fost g&#259;sit doar &icirc;n metoda Main.</span></p>
    <p class="c0"><span class="c5"></span></p>
    <p class="c4"><span class="c5">Output-ul &icirc;n consol&#259; al programului:</span></p>
    <p class="c0"><span class="c5"></span></p><a id="t.ea0089eb8ac0e172e93cf272f832ce0ed34daaf2"></a><a id="t.8"></a>
    <table class="c10">
        <tr class="c14">
            <td class="c6" colspan="1" rowspan="1">
                <p class="c3"><span class="c1">Bloc </span><span class="c2">finally</span><span
                        class="c1">&nbsp;&icirc;n Method2<br>Bloc </span><span class="c2">finally</span><span
                        class="c1">&nbsp;&icirc;n Method1<br>Catch &icirc;n Main: Attempted to divide </span><span
                        class="c2">by</span><span class="c1">&nbsp;zero<br>Bloc </span><span
                        class="c2">finally</span><span class="c1">&nbsp;&icirc;n Main<br>Sf&acirc;r&#537;itul metodei
                        Main</span></p>
            </td>
        </tr>
    </table>
    <p class="c0"><span class="c5"></span></p>
    <p class="c0"><span class="c5"></span></p>
</body>

</html>